# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-11 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='report',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='report',
            name='customer_id',
        ),
        migrations.RenameField(
            model_name='instances',
            old_name='networking',
            new_name='networking_seclist',
        ),
        migrations.RenameField(
            model_name='orchestration',
            old_name='oplans',
            new_name='inst_imagelist',
        ),
        migrations.AddField(
            model_name='orchestration',
            name='inst_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orchestration',
            name='inst_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orchestration',
            name='inst_shape',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instances',
            name='sshkeys',
            field=models.CharField(max_length=2047, null=True),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
