# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-11 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171211_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orchestration',
            old_name='inst_imagelist',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='orchestration',
            name='inst_label',
        ),
        migrations.RemoveField(
            model_name='orchestration',
            name='sccount',
        ),
    ]
