# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-11 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171211_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestration',
            name='inst_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
