# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-12 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orchestration_inst_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestration',
            name='inst_imagelist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orchestration',
            name='inst_seclist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
