# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-13 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171212_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instances',
            old_name='domain',
            new_name='inst_domain',
        ),
        migrations.RenameField(
            model_name='instances',
            old_name='name',
            new_name='inst_name',
        ),
        migrations.AlterUniqueTogether(
            name='instances',
            unique_together=set([('inst_name', 'api_id', 'customer_id')]),
        ),
    ]
