# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-13 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171213_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestration',
            name='private_ip',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orchestration',
            name='state',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orchestration',
            name='storage_attachments',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
