# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-13 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171213_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orchestration',
            name='storage_attachments',
        ),
        migrations.AddField(
            model_name='orchestration',
            name='storage',
            field=models.CharField(blank=True, max_length=2047),
        ),
    ]
