# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-13 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171213_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestration',
            name='imagelist',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orchestration',
            name='ssh_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
