# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-13 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171213_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orchestration',
            name='inst_imagelist',
        ),
    ]
