# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-14 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_orchestration_inst_imagelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestration',
            name='ipreserve',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
